#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_ENVIRONMENT') or define('YII_ENVIRONMENT', 'console');

require __DIR__ . '/config/environment_mode.php';

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

require __DIR__ . '/config/console.php';

$application = new yii\console\Application(YII_CONFIG);
$exitCode = $application->run();
exit($exitCode);
